# Generated by Django 4.2.1 on 2024-01-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=8)),
                ('year', models.IntegerField(default=1)),
                ('branch', models.CharField(default='', max_length=64)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=8)),
                ('year', models.IntegerField(default=1)),
                ('branch', models.CharField(default='', max_length=64)),
                ('content', models.ImageField(upload_to='img')),
                ('solution', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('page', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('content', models.ImageField(upload_to='img')),
                ('solution', models.ImageField(upload_to='img')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercice_book', to='main.book')),
            ],
        ),
    ]
