# Generated by Django 4.2.1 on 2024-01-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='book',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
