# Generated by Django 4.2.1 on 2024-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_exercice_book_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='content',
            field=models.ImageField(upload_to='main/media/img'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='solution',
            field=models.ImageField(upload_to='main/media/img'),
        ),
    ]
