# Generated by Django 4.2.1 on 2024-02-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exercice_content_alter_exercice_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='content',
            field=models.ImageField(upload_to='main/media/img'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='solution',
            field=models.ImageField(upload_to='main/media/img'),
        ),
        migrations.CreateModel(
            name='ExamImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/media/img')),
                ('isContent', models.BooleanField(default=True)),
                ('isSolution', models.BooleanField(default=False)),
                ('exam_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exampaper')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('cover', models.ImageField(upload_to='main/media/img')),
                ('file', models.FileField(upload_to='main/media/files')),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.field')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year')),
            ],
        ),
        migrations.AddField(
            model_name='exampaper',
            name='field',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercice',
            name='branch',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercice',
            name='field',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercice',
            name='level',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercice',
            name='year',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year'),
        ),
    ]
