# Generated by Django 4.2.1 on 2024-02-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_branch_field_level_year_alter_exampaper_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='examimg',
            options={'verbose_name_plural': 'Exam Images'},
        ),
        migrations.AlterField(
            model_name='book',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch'),
        ),
    ]
