# Generated by Django 4.2.1 on 2024-02-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_branch_options_alter_examimg_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='content',
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='solution',
        ),
    ]
