# Generated by Django 4.2.1 on 2024-02-09 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exampaper_branch_alter_exercice_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=255)),
                ('pubDate', models.DateField(default=datetime.date(1900, 1, 1))),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
