# Generated by Django 4.2.1 on 2024-02-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercice',
            old_name='content',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='solution',
        ),
        migrations.CreateModel(
            name='ExerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/media/img')),
                ('isContent', models.BooleanField(default=True)),
                ('isSolution', models.BooleanField(default=False)),
                ('exercice_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercice')),
            ],
            options={
                'verbose_name_plural': 'Exercice Images',
            },
        ),
    ]
